# Generated by Django 2.2.2 on 2019-08-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aura_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='email',
        ),
        migrations.AddField(
            model_name='securityagents',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='address_city',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='address_country',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='address_street',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='address_suburb',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='address_zip',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
