# Generated by Django 2.2.2 on 2019-08-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aura_backend', '0003_auto_20190808_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='license_number',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='plate_number',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
