# Generated by Django 2.2.2 on 2019-08-08 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aura_backend', '0004_auto_20190808_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securityagents',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
