# Generated by Django 2.2.2 on 2019-08-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aura_backend', '0005_auto_20190808_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='panics',
            name='client_phone_number',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='panics',
            name='client_username',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
