# Generated by Django 2.2.2 on 2019-08-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aura_backend', '0006_auto_20190808_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='panics',
            name='client_email',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
