# Generated by Django 2.2.2 on 2019-08-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aura_backend', '0007_panics_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panics',
            name='client_phone_number',
            field=models.IntegerField(default=None, max_length=250, null=True),
        ),
    ]
