# Generated by Django 2.2.2 on 2019-08-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aura_backend', '0008_auto_20190808_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panics',
            name='client_phone_number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
