# Generated by Django 2.2.2 on 2019-08-09 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aura_backend', '0011_auto_20190809_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicule',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='aura_backend.Companies'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicule',
            unique_together={('id', 'name', 'mark', 'license_number', 'plate_number')},
        ),
    ]
