# Generated by Django 2.2.2 on 2019-08-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aura_backend', '0012_auto_20190809_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicule',
            options={},
        ),
    ]
