# Generated by Django 2.2.2 on 2019-08-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aura_backend', '0013_auto_20190809_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicule',
            options={'ordering': ['id', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='vehicule',
            unique_together={('id', 'company_id', 'name', 'mark', 'license_number', 'plate_number')},
        ),
    ]
