# Generated by Django 2.2.2 on 2019-08-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aura_backend', '0015_auto_20190809_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityagents',
            name='current_location_region',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='securityagents',
            name='current_location_zip',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
