# Generated by Django 2.2.2 on 2019-08-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aura_backend', '0016_auto_20190809_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityagents',
            name='current_location_country',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='securityagents',
            name='current_location_region',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
