# Generated by Django 2.2.2 on 2019-08-10 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aura_backend', '0017_auto_20190809_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicule',
            options={'ordering': ['name']},
        ),
    ]
