# Generated by Django 2.2.2 on 2019-08-10 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aura_backend', '0018_auto_20190810_0806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicule',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='vehicule',
            unique_together=set(),
        ),
    ]
