# Generated by Django 2.2.2 on 2019-08-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aura_backend', '0019_auto_20190810_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicule',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='panics',
            name='panics_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='vehicule',
            unique_together={('id', 'company_id', 'name', 'mark', 'license_number', 'plate_number')},
        ),
    ]
