# Generated by Django 2.2.2 on 2019-08-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aura_backend', '0021_auto_20190810_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panics',
            name='panics_name',
            field=models.CharField(default='Emergency', max_length=250),
        ),
        migrations.AlterField(
            model_name='panics',
            name='panics_number',
            field=models.IntegerField(default=22165614),
        ),
        migrations.AlterField(
            model_name='panics',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
