# Generated by Django 2.2.2 on 2019-08-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aura_backend', '0022_auto_20190810_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panics',
            name='panics_name',
            field=models.CharField(default='Emergency', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='panics',
            name='panics_number',
            field=models.IntegerField(default=57269841),
        ),
    ]
