# Generated by Django 2.2.2 on 2019-08-11 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aura_backend', '0023_auto_20190810_0833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panics',
            options={'ordering': ['client_phone_number']},
        ),
        migrations.AlterField(
            model_name='panics',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panics', to='aura_backend.Companies'),
        ),
        migrations.AlterField(
            model_name='panics',
            name='panics_number',
            field=models.IntegerField(default=6573782),
        ),
        migrations.AlterUniqueTogether(
            name='panics',
            unique_together={('id', 'client_phone_number')},
        ),
    ]
