# Generated by Django 2.2.2 on 2019-08-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aura_backend', '0025_auto_20190811_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='ended_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='panics',
            name='panics_number',
            field=models.IntegerField(default=84660163),
        ),
    ]
