export const HOME_USERS_BEGIN = 'HOME_USERS_BEGIN';
export const HOME_USERS_SUCCESS = 'HOME_USERS_SUCCESS';
export const HOME_USERS_FAILURE = 'HOME_USERS_FAILURE';
export const HOME_USERS_DISMISS_ERROR = 'HOME_USERS_DISMISS_ERROR';

